/**
 * Builds public/rapid-recall/index.html and public/abg-ninja/index.html from the
 * standalone sources in RapidRecall/ and ABGNinja/.
 *
 * Unlike MedMatch these two are plain HTML/CSS/JS with no JSX and no libraries,
 * so there is nothing to transpile — the only change is the webfont link. In the
 * source it is a normal stylesheet, which blocks first paint on a render-blocking
 * round trip to fonts.googleapis.com. Because the games open inside an iframe on
 * a click, that delay lands exactly where it is most visible: the gap between
 * tapping the tile and seeing anything at all.
 *
 * The output is committed, like the crossword, Doctordle and MedMatch pages, so
 * this only needs re-running after editing either source:  npm run build:games
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const GAMES = [
  { src: 'RapidRecall/rapid-recall.html', out: 'public/rapid-recall/index.html', name: 'Rapid Recall' },
  { src: 'ABGNinja/abg-ninja.html', out: 'public/abg-ninja/index.html', name: 'ABG Ninja' },
];

/** The exact stylesheet link both games ship, and its non-blocking replacement. */
const FONT_LINK =
  '<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&family=IBM+Plex+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">';

const FONT_LINK_ASYNC = `<link rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&family=IBM+Plex+Sans:wght@400;500;600;700&display=swap"
      media="print" onload="this.media='all';this.onload=null">
<noscript>${FONT_LINK}</noscript>`;

const GENERATED_NOTE = (src) =>
  `<!-- Generated by scripts/build-games.mjs from ${src}.\n     Edit that file, not this one, then re-run the script. -->`;

for (const { src, out, name } of GAMES) {
  const html = readFileSync(resolve(root, src), 'utf8');

  if (!html.includes(FONT_LINK)) {
    throw new Error(
      `${src}: could not find the webfont <link> to make non-blocking.\n` +
      `If the fonts changed, update FONT_LINK in scripts/build-games.mjs to match.`
    );
  }

  let built = html.replace(FONT_LINK, FONT_LINK_ASYNC);

  // Drop a breadcrumb in the built file so nobody edits the wrong copy.
  built = built.replace('</head>', `${GENERATED_NOTE(src)}\n</head>`);

  const dest = resolve(root, out);
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, built);
  console.log(`wrote ${out} — ${(built.length / 1024).toFixed(0)} KB (${name})`);
}
